name: Audit Scan

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  build:
    name: Audit Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Audit Scan
        id: scan
        run: "gh api -H \"Accept: application/vnd.github+json\" -H \"X-GitHub-Api-Version: 2022-11-28\" /repos/Mortarco/${{ inputs.repo }}/code-scanning/alerts > scan.json"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Scan Result
        uses: actions/upload-artifact@v1
        with: 
          name: scan
          path: scan.json

      - name: Vuln Gate
        run: |
          count=$(cat scan.json | jq '.[] | select(.state == "open" and .rule.security_severity_level == "critical")' | jq -s .|jq length)
          if [ $count -ne 0 ] ; then
            echo $count vulnerability found ; exit 1
          fi
