name: Audit

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  scan-result:
    uses: ./.github/workflows/audit_scan.yml
    with:
      repo: ${{ inputs.repo }}


