name: Main

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: .github/workflows/security.yml@main
    with:
      name: sample
      path: PrivatePJ
      binary: target/sample-1.0.0-SNAPSHOT.jar
