name: Security

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      binary:
        required: true
        type: string

jobs:
  unit-test:
    uses: ./.github/workflows/unittest.yml
    with:
      path: ${{ inputs.path }}

  sast:
    uses: ./.github/workflows/sast.yml

  vuln:
    uses: ./.github/workflows/vuln.yml
    with:
      name: ${{ inputs.name }}
      path: ${{ inputs.path }}
      binary: ${{ inputs.binary }}


