name: Unit Test

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./${{ inputs.path }}

      - name: Test with Maven
        run: mvn --batch-mode test
        working-directory: ./${{ inputs.path }}

